// client/src/App.vue
<script setup lang="ts">
import { RouterView } from 'vue-router'
import { getSession } from './model/session'
import NavBar from './components/NavBar.vue';


const session = getSession()
</script>

<template>
  <header>
    <NavBar />
  </header>

  <div class="container">
    <progress class="progress is-small is-primary" max="100" v-if="session.loading">15%</progress>  
    <RouterView />
  </div>
</template>

<style scoped>
  body {
    background-color: rgb(18, 179, 179);
  }

  .container {
    background-color: white;
    box-shadow: 0 0 10px rgba(213, 16, 16, 0.1);
    padding: 5px;
    min-height: 100vh;
  }
</style>

// react/src/App.tsx
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'
import { BrowserRouter, Route, Routes } from 'react-router-dom'

const Navbar = () => <h1> NavBar </h1> 
const RouterView = () => <h1> RouterView </h1>
function App() {

  return (
    <>
      <BrowserRouter>
        <header>
          <Navbar />
        </header>

      <div className="container">
        <progress className="progress is-small is-primary" max="100" v-if="session.loading">15%</progress>  
        <Routes>
          <Route path="/" element={<div>Home</div>} />
          <Route path="/about" element={<RouterView />} />
          <Route path="/products" element={<RouterView />} />
        </Routes>
      </div>
      </BrowserRouter>
    </>
  )
}

export default App
